### PR TITLE
UPdate verbage

### PR DESCRIPTION
**Pull request by dtolb**

### CODE REVIEW

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-apdocs-testing-signed.s3-website-us-east-1.amazonaws.com/

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-apdocs-testing-signed.s3-website-us-east-1.amazonaws.com/

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-apdocs-testing-signed.s3-website-us-east-1.amazonaws.com/

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-apdocs-testing-signed.s3-website-us-east-1.amazonaws.com/

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-apdocs-testing-signed.s3-website-us-east-1.amazonaws.com/

**Comment by Jmainguy** [comment]
You da man.

**Pull request merged**
