### PR TITLE
added links to the faq in messaging

### PR DESCRIPTION
**Pull request by troft**

### CODE REVIEW

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-apdocs-v1-faq-link.s3-website-us-east-1.amazonaws.com/

**Comment by dtolb** [comment]
## Updated note

### Change
> NOTE: We only store the message contents for 30 days. Any messages older than 30 days will not contain text.

### To

> Bandwidth stores both inbound and outbound messages for 30 days. For more information see the [FAQ](http://dev.bandwidth.com/faq/#messaging)

## Screen shots
Change up the alert on the fetch message info page:

pic

Same thing to the all messages

all

**Comment by troft** [comment]
I fixed it to add the notes.

**Comment by dtolb** [comment]
Preview Changes at:
        http://bw-apdocs-v1-faq-link.s3-website-us-east-1.amazonaws.com/

**Pull request merged**
